# Generated by Django 3.2.16 on 2024-06-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор объявления'),
        ),
    ]
